name: Make changelogs

on:
  push:
    branches: [master]

jobs:
  MakeCL:
    runs-on: ubuntu-latest
    if: (!contains(github.event.head_commit.message, '[ci skip]'))
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 25
      - name: Python setup
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml PyGithub pyyaml bs4
      - name: Make CL
        env:
          GITHUB_TOKEN: ${{ secrets.CL_TOKEN }}
        run: python tools/changelog/generate_cl.py
      - name: Compile CL
        run: python tools/changelog/ss13_genchangelog.py html/changelog.html html/changelogs
      - name: Commit
        run: |
          git config --local user.email "aquila33-bot@protonmail.com"
          git config --local user.name "aquila33-bot"
          git commit -m "Automatic changelog compile [ci skip]" -a || true
          git pull --rebase origin master
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CL_TOKEN }} 
